### ISSUE TITLE
Security Data Issues - Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [jkresner/argu.37#1]
Hi ,

url : https://github.com/jkresner/argu.37/blob/9628a50a8fae02f44cfe8d571278f03c92d30716/_/server/cfg/app.prod.env

have commit that need to remove from the github history
attacker can see it and use it ...

encrypt your secrets !!!!

Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕

**Comment by jkresner** [comment]
yeah … I'm too lazy, busy to care and this site doesn't actually exist, but I'll tip you if you feel like cleaning up the commit history for me 😁
