### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [jkresner/argu.37#2]
Hi,<br><br>url : https://github.com/jkresner/argu.37/blob/9628a50a8fae02f44cfe8d571278f03c92d30716/_/server/cfg/app.prod.env <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by jkresner** [comment]
🙏 I appreciate where you are coming from. You are right and everyone should follow your advice.

㊙️ There are special circumstances at play in the 𝑓″universe, for which this level of security have no consequence. My desire is for the information to be as accessible as possible to facilitate certain algorithms at play.
